safe: false
lsi: false
rouge: true
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
permalink: /blog/:year/:month/:title.html
encoding: utf-8